# Generated by Django 4.2.7 on 2023-11-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forex", "0002_remove_userprofile_email_remove_userprofile_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
