# Generated by Django 4.2.7 on 2023-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forex", "0003_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
