# Generated by Django 4.2.7 on 2023-11-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forex", "0004_userprofile_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
