# Generated by Django 4.2.7 on 2023-11-28 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forex", "0006_order_passwordresetrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
    ]
