# Generated by Django 4.2.7 on 2023-11-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forex", "0007_remove_userprofile_email_remove_userprofile_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
