# Generated by Django 4.2.7 on 2023-11-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forex", "0008_alter_order_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
