# Generated by Django 4.2.7 on 2023-11-29 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forex", "0012_order_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
